# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# import os
# import sys
# sys.path.insert(0, os.path.abspath('.'))


# -- Project information -----------------------------------------------------

project = 'LuatOS'
copyright = 'LuatOS团队'
author = 'luatos'


# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'myst_parser',
    'sphinx_sitemap',
    'sphinx_copybutton',
]


# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']
html_js_files = [
    'js/baidu.js',
    'js/a.js',
]

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'zh_CN'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = ["README.md"]


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'furo'
pygments_style = "vs"
pygments_dark_style = "monokai"
primary_color = "#0094ff"
darker_primary_color = "#007bd3"
html_theme_options = {
    "sidebar_hide_name": True,
    "navigation_with_keys": True,
    "light_logo": "logo.svg",
    "dark_logo": "logo-light.svg",
}
html_css_files = [
    'css/theme-overrides.css',
    'css/run-code.css',
]

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']


html_show_sphinx = False
html_search_language = 'zh'
html_baseurl = 'https://wiki.luatos.com/'
sitemap_url_scheme = "{link}"
html_copy_source = False

myst_enable_extensions = [
    "html_admonition",
]
